/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tongketjava2;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author MyPC
 */
public class GiaoDien extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDien
     */
    public GiaoDien() {
        
        initComponents();
        KQ.setText((count)+" of "+ (Total)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfAge = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfSalary = new javax.swing.JTextField();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnOpenFile = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        KQ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần Mềm Quản Lý Nhân Sự");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("EMPLOYEE MANAGEMENT");

        jLabel2.setText("Employee ID");

        jLabel3.setText("Name");

        jLabel4.setText("Age");

        jLabel5.setText("Address");

        jLabel6.setText("Email");

        jLabel7.setText("Salary");

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnOpenFile.setText("Open File");
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpenFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOpenFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addGap(4, 4, 4)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addGap(7, 7, 7))
        );

        jLabel8.setText("Record:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(229, 229, 229))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)))))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfID)
                            .addComponent(tfName)
                            .addComponent(tfAge)
                            .addComponent(tfAddress)
                            .addComponent(tfEmail)
                            .addComponent(tfSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(btnFirst))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNext)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLast))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(KQ)))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFirst)
                            .addComponent(btnPrevious)
                            .addComponent(btnNext)
                            .addComponent(btnLast)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(KQ))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {                                       
        tfName.setText("");
        tfID.setText("");
        tfAddress.setText("");
        tfSalary.setText("");
        tfEmail.setText("");
        tfAge.setText("");
         KQ.setText((count+1)+" of "+ (Total));
    }                                      

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {                                            
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(this);
        File file = chooser.getSelectedFile();
        filename=file.getAbsolutePath();
        ObjectInputStream out=null;
        FileInputStream f = null;
        try {
            f = new FileInputStream(filename);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GiaoDien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        try
        {
        out = new ObjectInputStream(f);
        while(f.available()>0)
        {
         Employee temp = (Employee) out.readObject();
         nv.add(temp);
        }
                Total=nv.size();
                count=0;
                tfName.setText(nv.get(0).getName());
                tfID.setText(nv.get(0).getId());
                tfAddress.setText(nv.get(0).getAddress());
                tfSalary.setText(nv.get(0).getSlary()+"");
                tfEmail.setText(nv.get(0).getEmail());
                tfAge.setText(nv.get(0).getAge());
                KQ.setText((count+1)+" of "+ (Total));
        }
        catch( ClassNotFoundException e)
        {
            System.out.println(e.getException());
        } catch (IOException ex) {
            Logger.getLogger(GiaoDien.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        finally
        {
            try {
                if(out!=null)
                {
                    try {
                        out.close();
                    } catch (IOException ex) {
                        Logger.getLogger(GiaoDien.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                f.close();
            } catch (IOException ex) {
                Logger.getLogger(GiaoDien.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }                                           

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {                                        
      
                    Employee nv1 = new Employee();
                    nv1.setId(tfID.getText().toString());
                    nv1.setName(tfName.getText().toString());
                    nv1.setAge(tfAge.getText().toString());
                    nv1.setEmail(tfEmail.getText().toString());
                    nv1.setAddress(tfAddress.getText().toString());
                    nv1.setSlary(Double.parseDouble(tfSalary.getText().toString()));
                    nv.add(nv1);
                    count++;
                    Total=nv.size();
                    KQ.setText((count)+" of "+ (Total));
    }                                       

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        Object[] options={"Lưu File Mới","Ghi Vào File Cũ","Thoát Chương Trình"};
       // Total=nv.size();
        
       int check= JOptionPane.showOptionDialog(this,"Bạn muốn lưu dữ liệu không?", "Lưu File",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[2]);
       if(check==JOptionPane.YES_OPTION)
       {
           FileOutputStream fos = null;
            try {
                JFileChooser chooser = new JFileChooser();
                chooser.showSaveDialog(this);
                File file=chooser.getSelectedFile();
                String filename2=file.getAbsolutePath();
                fos = new FileOutputStream(filename2);
                ObjectOutputStream oos=new ObjectOutputStream(fos);
                for(int i=0;i<nv.size();i++)
                {
                oos.writeObject(nv.get(i));
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GiaoDien.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(GiaoDien.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    fos.close();
                } catch (IOException ex) {
                    Logger.getLogger(GiaoDien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
           
       }
       else if(check==JOptionPane.NO_OPTION)
       {
                FileOutputStream fos = null;
            try {
                
                fos = new FileOutputStream(filename);
                ObjectOutputStream oos=new ObjectOutputStream(fos);
                for(int i=0;i<nv.size();i++)
                {
                oos.writeObject(nv.get(i));
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GiaoDien.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(GiaoDien.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    fos.close();
                } catch (IOException ex) {
                    Logger.getLogger(GiaoDien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
       {
           
       }
       
       }
       else
       {
          System.exit(0);
       }
    }                                       

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
                  count=0;
                  tfID.setText(nv.get(count).getId());
                  tfName.setText(nv.get(count).getName());
                  tfAge.setText(nv.get(count).getAge());
                  tfEmail.setText(nv.get(count).getEmail());
                  tfAddress.setText(nv.get(count).getAddress());
                  tfSalary.setText(nv.get(count).getSlary()+"");
                  KQ.setText((count+1)+" of "+ (Total));
    }                                        

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if(count>0)
        {
                    count--;
                    tfID.setText(nv.get(count).getId());
                  tfName.setText(nv.get(count).getName());
                  tfAge.setText(nv.get(count).getAge());
                  tfEmail.setText(nv.get(count).getEmail());
                  tfAddress.setText(nv.get(count).getAddress());
                  tfSalary.setText(nv.get(count).getSlary()+"");
                  KQ.setText((count+1)+" of "+ (Total));
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Đây là nhân viên đầu tiên");
        }
    }                                           

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
                  count=nv.size()-1;
                  tfID.setText(nv.get(count).getId());
                  tfName.setText(nv.get(count).getName());
                  tfAge.setText(nv.get(count).getAge());
                  tfEmail.setText(nv.get(count).getEmail());
                  tfAddress.setText(nv.get(count).getAddress());
                  tfSalary.setText(nv.get(count).getSlary()+"");
                  KQ.setText((count+1)+" of "+ (Total));
    }                                       

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        if(count<nv.size()-1)
        {
                    count++;
                    tfID.setText(nv.get(count).getId());
                  tfName.setText(nv.get(count).getName());
                  tfAge.setText(nv.get(count).getAge());
                  tfEmail.setText(nv.get(count).getEmail());
                  tfAddress.setText(nv.get(count).getAddress());
                  tfSalary.setText(nv.get(count).getSlary()+"");
                  KQ.setText((count+1)+" of "+ (Total));
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Đây là nhân viên cuối cùng");
        }
    }                                       

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        try
        {
            if(count==0)
            {
                
                nv.remove(nv.get(count));
                tfID.setText(nv.get(count).getId());
                tfName.setText(nv.get(count).getName());
                tfAge.setText(nv.get(count).getAge());
                tfEmail.setText(nv.get(count).getEmail());
                tfAddress.setText(nv.get(count).getAddress());
                tfSalary.setText(nv.get(count).getSlary()+"");
                Total--;
                KQ.setText((count+1)+" of "+ (Total));
                
            }
            else
            {
               
            nv.remove(nv.get(count));
            count--;
            Total--;
            tfID.setText(nv.get(count).getId());
            tfName.setText(nv.get(count).getName());
            tfAge.setText(nv.get(count).getAge());
             tfEmail.setText(nv.get(count).getEmail());
             tfAddress.setText(nv.get(count).getAddress());
             tfSalary.setText(nv.get(count).getSlary()+"");
             KQ.setText((count+1)+" of "+ (Total));
                System.out.println(Total+"/"+count);
             }
        }
        catch(IndexOutOfBoundsException e)
        {
            Total=nv.size();
            System.out.println(nv.size());
            tfName.setText("");
            tfID.setText("");
            tfAddress.setText("");
            tfSalary.setText("");
             tfEmail.setText("");
            tfAge.setText("");
            KQ.setText((count)+" of "+ (Total));
        }
        
       
    }                                         

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String check=JOptionPane.showInputDialog(this,"Nhập ID cần tìm:");
        if(nv.size()==0)
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa có dữ liệu!");
        }
        for(int i=0;i<nv.size();i++)
        {
            if(nv.get(i).getId().equalsIgnoreCase(check))
            {
                tfName.setText(nv.get(i).getName());
                tfID.setText(nv.get(i).getId());
                tfAddress.setText(nv.get(i).getAddress());
                tfSalary.setText(nv.get(i).getSlary()+"");
                tfEmail.setText(nv.get(i).getEmail());
                tfAge.setText(nv.get(i).getAge());
                KQ.setText((i)+" of "+ (nv.size()));
            }
        }
    }                                       
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDien().setVisible(true);
            }
        });
    }
 private ArrayList<Employee> nv = new ArrayList<>();
 private int Total=0;
 private int count=0;
 private String filename;
    // Variables declaration - do not modify                     
    private javax.swing.JLabel KQ;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSalary;
    // End of variables declaration                   
}
